Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [2]:
import numpy as np
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


🌟 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:



array([3, 2, 0, 1, 2])


In [3]:
my_list = [3.14, 2.17, 0, 1, 2]
my_array = np.array(my_list, dtype=int)
my_array

array([3, 2, 0, 1, 2])

Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


In [4]:
array_3x3 = np.arange(1, 10).reshape(3, 3)
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])


In [6]:
random_array=np.random.rand(4,5)
random_array

array([[0.47865744, 0.11955589, 0.52754673, 0.65573978, 0.45315256],
       [0.28697983, 0.02879517, 0.94928081, 0.7504047 , 0.5114779 ],
       [0.69867081, 0.75475424, 0.43439316, 0.03746867, 0.6057036 ],
       [0.59224292, 0.42370172, 0.60737186, 0.36626102, 0.93604957]])

Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])


In [7]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
second_row = array[1]
second_row

array([20, 21, 22, 23, 24])

Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [11]:
array= np.arange(10)
reversed_array = np.flip(array)
reversed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


In [12]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5


In [16]:
array = np.arange(10)
array_sum = np.sum(array)
array_avg = np.mean(array)
print(f"Sum: {array_sum}, Average: {array_avg}")

Sum: 45, Average: 4.5


 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


In [21]:
array = np.arange(1, 21).reshape(4, 5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])


In [23]:
array = np.arange(10)
odd_numbers = array[array % 2 != 0]
odd_numbers
even_numbers = array[array % 2 == 0]
even_numbers

array([0, 2, 4, 6, 8])