Exercise 1 : Minimum and Maximum of Random Array
Instructions
Create a 5x5 array with random values and find the minimum and maximum values.

Expected Output:



Min: 0.01, Max: 0.99


In [4]:
import numpy as np
array = np.random.rand(5,5)
min_value = np.min(array)
max_value = np.max(array)
print(f"Min: {min_value:.2f}, Max: {max_value:.2f}")

Min: 0.02, Max: 0.94


Exercise 2 : Matrix Normalization
Instructions
Normalize a 3x3 random matrix (subtract the mean and divide by the standard deviation of the matrix).

Expected Output:



array([[-1.22474487,  1.22474487],
       [ 0.        ,  0.        ]])


In [5]:
array = np.random.rand(3,3)
mean = np.mean(array)
std = np.std(array)
normalized_array = (array - mean) / std
print(normalized_array)


[[-0.83473667  0.40517522  0.96846332]
 [ 0.9354738   0.58263129  0.12897222]
 [-1.70710921 -1.45208542  0.97321545]]


Exercise 3 : Evenly Spaced Elements in Array
Instructions
Create a 1D array of 50 evenly spaced elements between 0 and 10, exclusive.

Expected Output:



array([0. , 0.2, 0.4, ..., 9.6, 9.8, 10.])


In [7]:
array = np.linspace(0, 10, 50)
array

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])


Exercise 4 : Matrix Multiplication
Instructions
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

Expected Output:



array([[ 8.79,  6.73],
       [12.87,  9.77],
       [16.92, 12.83],
       [20.98, 15.89],
       [25.04, 18.95]])


In [11]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)

result_matrix = np.dot(matrix1, matrix2)
result_matrix


array([[1.12571082, 0.95783693],
       [1.42862419, 1.82240824],
       [1.00811085, 1.1502392 ],
       [0.84890345, 0.714316  ],
       [0.61612531, 0.42653801]])

Exercise 5
Instructions
Utilize your understanding of matrix multiplication to solve this exercise.
Create two matrices of compatible dimensions.
Perform matrix multiplication on these matrices and display the result.
Ensure the dimensions of the matrices allow for valid multiplication.
Tip: Remember that the number of columns in the first matrix should match the number of rows in the second matrix for successful multiplication.



In [15]:
y = np.array([[1, 6], [3, 9]])
x = np.array([[5, 12], [4, 8]])
result_matrix = np.dot(y, x)
result_matrix
result_matrix=x@y
print(result_matrix)

[[ 41 138]
 [ 28  96]]
