Exercise 1 : Maximum Value Replacement in Matrix
Instructions
Create a random 5x5 matrix and replace the maximum value by 0.

Expected Output:



array([[0.23, 0.35, 0.01, 0.05, 0.11],
       [0.91, 0.28, 0.66, 0.13, 0.14],
       [0.94, 0.40, 0.76, 0.65, 0.46],
       [0.12, 0.15, 0.95, 0.57, 0.60],
       [0.17, 0.97, 0.87, 0.45, 0.  ]])


In [2]:
import numpy as np
array = np.random.rand(5,5)
max_value = np.max(array)
array[array == max_value] = 0
print(array)

[[0.67062433 0.7722392  0.0518804  0.2233197  0.13709625]
 [0.21838938 0.81430769 0.84335229 0.59387556 0.3434281 ]
 [0.92091265 0.69490765 0.29079715 0.74540712 0.60614749]
 [0.31962295 0.44047365 0.81462827 0.15831446 0.83764058]
 [0.63391597 0.03317431 0.06705404 0.28453199 0.30070019]]
[[0.67062433 0.7722392  0.0518804  0.2233197  0.13709625]
 [0.21838938 0.81430769 0.84335229 0.59387556 0.3434281 ]
 [0.         0.69490765 0.29079715 0.74540712 0.60614749]
 [0.31962295 0.44047365 0.81462827 0.15831446 0.83764058]
 [0.63391597 0.03317431 0.06705404 0.28453199 0.30070019]]


Exercise 2 : Finding Common Values in Arrays
Instructions
Find the common values between two random arrays of size 5.

Expected Output:



array([0.35, 0.66, 0.76])


In [16]:
array1 = np.random.rand(5)
array2 = np.random.rand(5)
common_values = np.intersect1d(array1, array2)
common_values

array([], dtype=float64)

Exercise 3 : Sorting Array in Ascending and Descending Order
Instructions
Create a random 1D array of size 10 and sort it in ascending and then in descending order.

Expected Output:



Ascending: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
Descending: array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1])


In [17]:
array = np.random.rand(10)
ascending_array = np.sort(array)
descending_array = np.sort(array)[::-1]
print("Ascending:", ascending_array)
print("Descending:", descending_array)

Ascending: [0.04533868 0.2440671  0.4287164  0.53485228 0.55602814 0.57796912
 0.64742497 0.69472741 0.78364877 0.86204116]
Descending: [0.86204116 0.78364877 0.69472741 0.64742497 0.57796912 0.55602814
 0.53485228 0.4287164  0.2440671  0.04533868]


Exercise 4 : Matrix Rank Determination
Instructions
Generate a random 4x4 matrix and find the rank of the matrix.

Expected Output:



Rank: 4


In [20]:
matrix = np.random.rand(4, 4)
rank = np.linalg.matrix_rank(matrix)
print("Rank:", rank)
matrix

Rank: 4


array([[0.08777383, 0.1312021 , 0.34259977, 0.65392982],
       [0.18051899, 0.38592798, 0.87211019, 0.334852  ],
       [0.16191562, 0.31759647, 0.41352054, 0.14257977],
       [0.18307866, 0.56959569, 0.74022662, 0.22468111]])

Exercise 5 : Creating Border Array
Instructions
Create a 2D array with 1 on the border and 0 inside.

Expected Output:



array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])


In [25]:
array = np.zeros((4,8))
array[0,:]=1
array[-1:]=1
array[:,0]=1
array[:,-1]=1
array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])